### ISSUE TITLE
cant import sql

### ISSUE THREAD

**Issue by themadscientistcreations** [ESX-Org/esx_jobs#101]
i have all the required dependencys and such but it will not let me import the sql for the dang thing.

![image](https://user-images.githubusercontent.com/45185041/74066885-fff73f00-49c5-11ea-9b90-c0c4a3fe0dce.png)

**Comment by CrazyMicka** [comment]
It's already on you database check you're addon_account table

**Comment by l3op** [comment]
I guess this error shown because there's a missing column in the item table which is `limit` column.
