### ISSUE TITLE
nothing happens on markers

### ISSUE THREAD

**Issue by bsk193** [ESX-Org/esx_jobs#112]
so the title says everything
nothing happens on markers at least on the lumberjack don't know about other ones
also trying manually add wood and cut it and nothing happens its like its not triggering the action

**Comment by Deliux** [comment]
yes, using latest version, same thing. It actually happens but it's delayed, you press E, sometimes you wait some time and you starting to get items, others times you get nothing, really frustratint, I think it has something to do with latest esx player positions/coords updating maybe?

**Comment by bsk193** [comment]
looks like its very delayed like some times it does't go inside the ifs, i'm try to rewrite it

**Comment by bsk193** [comment]
okay as probably u know is a server side problem when it tries to identify which zone u are.
and by what i can see its in this for:
`for i,v in ipairs(data.jobItem) do`

still trying to identify the problem

**Comment by bakerzone** [comment]
I've tested them all and they all appear to have the same issue, you can get them to work mostly by standing still at the exact moment that the "E" to start appears, except rock cleaning where I gave up after 15 minutes.
