### ISSUE TITLE
Not so much an issue, but need help with this ESX Job.

### ISSUE THREAD

**Issue by anthonybeatz22** [ESX-Org/esx_jobs#113]
Sorry I have been going everywhere but decided to just ask the source. Basically for these jobs I want to remove the fact that you have to go to the locker room, change and then you can either spawn a work truck or work as needed.

I am setting up where players can just create Peds via the MP Ped in vMenu, but when I go to the locker room (or cloak room) the model changes back to the default one.

That's all I am wondering how to do, is how to trigger a job without having the ped model change.

(P.s I tried to take out the esx_skin but that completely made jobs not show up)

**Comment by bsk193** [comment]
just change where says onDuty to true
that way you will allways be onDuty

**Comment by anthonybeatz22** [comment]
> just change where says onDuty to true
> that way you will allways be onDuty

Dude....thank you so damn much. That did it.
