### ISSUE TITLE
de_esx_jobs.sql is missing skins

### ISSUE THREAD

**Issue by RalFingerLP** [ESX-Org/esx_jobs#12]
Line 24-26

  ('textil', 0, 'interim', 'Mitarbeiter', 0, '{}', '{}'),
  ('miner', 0, 'interim', 'Mitarbeiter', 0, '{}', '{}'),
  ('slaughterer', 0, 'interim', 'Mitarbeiter', 0, '{}', '{}')

Is missing the skin information in the _de localization.

**Comment by ElPumpo** [comment]
Thanks for letting us know, fixed.
