### ISSUE TITLE
No Job Center/Job Markers

### ISSUE THREAD

**Issue by Jarrrk** [ESX-Org/esx_jobs#13]
Installed the resource with all specified pre-requisites, resource loads fine.

The public zones work but don't load the IPL's for the interiors or have a blip if the boolean is set to true. (Guessing because there's no sprite set?)

Main issue being no jobs are available, no markers on the map, if I teleport to the fishing cloakroom or any other co-ordinates there's nothing there.

There's no documentation on the resource besides the install, I'm confused if there's extra configuration that I'm simply missing.

Any help would be appreciated, cheers.

**Comment by RomainLanz** [comment]
Use this https://github.com/ESX-Org/esx_joblisting

**Comment by Jarrrk** [comment]
@RomainLanz is this to be used like a wrapper? So I load esx_jobs as well?

**Comment by RomainLanz** [comment]
`esx_jobs` only bring job to your server, if you want a way to list them or apply to them use this resource.
