### ISSUE TITLE
Job fuel no car spawn.

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_jobs#15]
Job fuel no car spawn at all.

**Comment by TanguyOrtegat** [comment]
same, it spawns 1/2 weird...

**Comment by TanguyOrtegat** [comment]
i know the issue, just clear the area and it will spawn

**Comment by renaiku** [comment]
clear what ?

**Comment by TanguyOrtegat** [comment]
the spawnarea

**Comment by ElPumpo** [comment]
Related to #31, closing
