### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_jobs#28]
Error resuming coroutine: server/esx_jobs_sv.lua:56: attempt to index a nil value (local 'xPlayer')
stack traceback:
	server/esx_jobs_sv.lua:56: in function <server/esx_jobs_sv.lua:47>

What is this error?

**Comment by ElPumpo** [comment]
Seems like the source got lost, or possibly when someone leaves an job marker. This can be fixed (in drugs aswell) by comparing `xPlayer` to `nil`

**Comment by HumanTree92** [comment]
I have never had this problem till just now. How would i go about fixing this?

**Comment by ElPumpo** [comment]
Should be fixed in 27b0f8253b6cccdd58d651514e9c18619eb20586, reopen if it doesn't fix the issue.
