### ISSUE TITLE
My MySQL Database Error Code (1146) "essentialmode.jobs" doesn't exist 

### ISSUE THREAD

**Issue by Mudzey** [ESX-Org/esx_jobs#29]
I followed all instructions adding all required scripts to my server database with MySQL. 
I pretty much have most off the mods that does not need, as I have explained above I checked. 
Please come back to me with a quick reply as I would love to start this server soon!

**Comment by ElPumpo** [comment]
You have not installed the dependencies correctly.

**Comment by hacklover** [comment]
This is esx_jobs, there is

INSERT INTO `jobs` (name, label) VALUES

but no CREATE TABLE `jobs`

**Comment by ElPumpo** [comment]
Esx (duh)

**Comment by miladzamir** [comment]
i have this problem but i don't understand can u say again and explanation more
**_sql error 1146 table essentialmode jobs doesn't exist_**
and i install all dependencies correctly.

**Comment by MedAmr** [comment]
where did you find the SQL create table job?
