### ISSUE TITLE
Vehicle wont spawn but will still take caution when spawnpoint isn't clear

### ISSUE THREAD

**Issue by ElRocaYT** [ESX-Org/esx_jobs#31]
I'm trying to fix it by myself (Not fixed yet)
When you spawn a Job car of the spawn point area is clear the vehicle spawn and take the money, but if is a car blocking the spawn point area the vehicle doesnt spawn but the script take the caution anyway and people lose money.

**Comment by ElPumpo** [comment]
Resolved in 71b80da8b9928e397fc4a6527ff585fb39d4120e
