### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/esx_jobs#32]
- Improve CurrentAction (take from policejob or something)
- Refactor code / use functions from ESX instead of e.g spawning vehicles the old way
    - spawning vehicle
    - sending notification
    - more?

**Comment by Olympz** [comment]
Hi there! now ive resinstalled my server twice, and i still get this problem.
I go to the Job center and i press E but nothings happening, can you please help me with this. 
I will send you a picture of what the serverlog says when i press E.
![whyn dont my job work](https://user-images.githubusercontent.com/40069758/41511100-c9b37d88-7270-11e8-92b4-5e1f9757608b.png)

**Comment by ElPumpo** [comment]
ab491550bec7e6e11ad622d24e7f36eefec77224
