### ISSUE TITLE
Move caution to server-side

### ISSUE THREAD

**Issue by LuaDeldu** [ESX-Org/esx_jobs#33]
In order to avoid cheatengine injection because client-sided values can be modified by listening with cheatengine.

**Comment by Xseba360** [comment]
This is very much needed. A cheater just joined our server today and got ridiculous amounts of money by damaging his car on the slaughterer/miner job and modifying the values with cheat engine.

**Comment by ElPumpo** [comment]
For now rename the event names...

**Comment by Jeffrey-Lang** [comment]
Renaming events won't make a difference they look up for example 2000 and they edit the value to 1000000 and that will be send to the server script which then pays out the 1000000

Maybe an idea to set prices in the database? I could help make that

**Comment by ElPumpo** [comment]
No?? The solution is simply to have the code server-sided.

**Comment by SwAtRaNgEr** [comment]
still an issue.
