### ISSUE TITLE
Starting Error

### ISSUE THREAD

**Issue by Rekiem94** [ESX-Org/esx_jobs#35]
We still getting error when we start our server. See the screenshot below.

![018fc19be232ded6e065d5479977321c](https://user-images.githubusercontent.com/7758205/39660972-50a7b154-504a-11e8-8158-200cae09ca71.png)

**Comment by ElPumpo** [comment]
Not related to esx_jobs, neither is this is a issue with the script. You're missing society information in the sql, and update esx_society
