### ISSUE TITLE
Some clients don't see circle waypoints for jobs

### ISSUE THREAD

**Issue by grimmdev** [ESX-Org/esx_jobs#52]
So I setup Fivem, and ESX, the requirements for ESX_Jobs I also setup the database. However when I join one of the jobs in this resource, it works almost 100%. I can see the waypoints for job actions and vehicles, however when someone else joins the server, they don't see the circles. Is there something I'm missing?

**Comment by ElPumpo** [comment]
Yea you're missing something.
