### ISSUE TITLE
Cheat Engine issue

### ISSUE THREAD

**Issue by Jeffrey-Lang** [ESX-Org/esx_jobs#53]
People can use Cheat Engine when they deliverer the car they rented like the lumberjob and mining job.

While the amount of money is set by the client script they can edit this with Cheat Engine.

**Comment by ElPumpo** [comment]
#33

**Comment by EbenSantuy** [comment]
you need to set the selling price with only 3 numbers , like 1 chicken is only 200 if you set the chicken sell is 2000 the cheat engine will works
