### ISSUE TITLE
es_extended/server/main.lua:163 error jobs 

### ISSUE THREAD

**Issue by Lyccossa** [ESX-Org/esx_jobs#70]
hello guys I have the following problem but I understand why, I'm doing hell.

Could you help me please?
![FOTO 3](https://user-images.githubusercontent.com/33160324/55638023-a8cc8080-579c-11e9-9a77-328c094f10bc.png)
![foto 4](https://user-images.githubusercontent.com/33160324/55638024-a8cc8080-579c-11e9-8f16-b787f1d59be1.png)
![foto 5](https://user-images.githubusercontent.com/33160324/55638026-a8cc8080-579c-11e9-91f8-007e2b769d93.png)

**Comment by RedAlex** [comment]
This is missing in your data base
https://github.com/ESX-Org/es_extended/blob/51b2df94aff1ac31e31256d7a2a81a4e75a51cd2/es_extended.sql#L35
