### ISSUE TITLE
Bug fast working when jump in and out work zone !

### ISSUE THREAD

**Issue by jamesfill** [ESX-Org/esx_jobs#79]
I found a bug when you jump in and out of work zone the time to collect items run very fast and you just need a sort time time to do the work !

Have any idea to fix it ?

**Comment by JeanClode** [comment]
I just put a timeout immediately after someone goes out of the zone, forcing them to wait the harvest time before they can activate the harvest option again.

**Comment by hotatchanh** [comment]
> I just put a timeout immediately after someone goes out of the zone, forcing them to wait the harvest time before they can activate the harvest option again.

Hi can you share me your timeout code ?

**Comment by Pengich** [comment]
> I just put a timeout immediately after someone goes out of the zone, forcing them to wait the harvest time before they can activate the harvest option again.

Can you share the fix for this?

**Comment by Tinky124** [comment]
> I just put a timeout immediately after someone goes out of the zone, forcing them to wait the harvest time before they can activate the harvest option again.

Can you share with us please?

**Comment by Adam-rGz** [comment]
@Tinky124  @Pengich @hotatchanh 
https://github.com/ESX-Org/esx_jobs/pull/81
