### ISSUE TITLE
Constant Tick duration issues.

### ISSUE THREAD

**Issue by Jordo999** [ESX-Org/esx_jobs#80]
Ran a recourse monitor and found that esx_jobs is constantly taking longer and longer each server tick.

[img](https://i.imgur.com/R3zhqtf.png)

**Comment by Ex0r** [comment]
I have this exact same issue. It gets to a point where in console, I get up to nearly 20,000ms in thread hitch warnings and haven't been able to locate it. After running utw I found that after 20 minutes while it was causing issues, I had similar results.
