### ISSUE TITLE
ESX Weight support

### ISSUE THREAD

**Issue by RoJea32** [ESX-Org/esx_jobs#92]
@ElPumpo @rex2630 Are you planning on updating the script for ESX Weight support soon? :)

**Comment by rex2630** [comment]
Maybe i can look on that

**Comment by RoJea32** [comment]
That's nice. Thank you!

**Comment by bandidom9** [comment]
This is trying to insert limits on item table but latest es_extended doesn't have a limit field. not sure if is es_extended that is wrong.

**Comment by YuriZoko** [comment]
I have send ai have send pull request, wait a moment

**Comment by DNDdjay** [comment]
Hi when do u think u Will make it with weight system. For can't wait to have this script on My server

**Comment by YuriZoko** [comment]
I proposed the modification to the creator, if he accepts the version with the weight management will be directly on the github
